version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000   
    volumes:
      - .:/app                                            
    restart: unless-stopped                               

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
